
condor:
  event_fraction: 10
  grouping_amount_data: 50
  #54732/50
  njobs: 1

#Folders for dumping large number of events
locations:
  offline:  
    #have root://submit50.mit.edu// in front 
    dump: mori25/dark_photons_ludo/DimuonTrees/test_off/dump/
    logs: /data/submit/mori25/dark_photons_ludo/DimuonTrees/test_off/logs/
    Jpsi: /data/submit/mori25/dark_photons_ludo/DimuonTrees/test_off/Jpsi/
    Y: /data/submit/mori25/dark_photons_ludo/DimuonTrees/test_off/Y/
  MC:  
    #have root://submit50.mit.edu// in front
    dump: mori25/dark_photons_ludo/DimuonTrees/test_MC/dump/
    logs: /data/submit/mori25/dark_photons_ludo/DimuonTrees/test_MC/logs/
    Jpsi: /data/submit/mori25/dark_photons_ludo/DimuonTrees/test_MC/Jpsi/
    Y: /data/submit/mori25/dark_photons_ludo/DimuonTrees/test_MC/Y/


#Section for training 
BDT_training:
  Y:
    limits:
      inclusive: (8.5,11.2)
      signal: 
        - ()
      background:
        - ()
        - ()
    train_vars:
      - Mm_kin_lxy
      - Mm_kin_l3d
      - Mm_kin_sl3d
      - Mm_kin_vtx_chi2dof
      - Mm_kin_vtx_prob
      - Mm_kin_alpha
      - Mm_kin_alphaBS
      - Mm_closetrk
      - Mm_closetrks1
      - Mm_closetrks2
      - Mm_kin_pvip
      - Mm_kin_spvip
      - Mm_kin_eta    
      - Mm_kin_pvlip
      - Mm_kin_slxy
      - Mm_iso
      - Mm_otherVtxMaxProb
      - Mm_otherVtxMaxProb1
      - Mm_otherVtxMaxProb2
    other_vars:
      - Mm_mass
      - Mm_mu1_pt
      - Mm_mu1_eta
      - Mm_mu1_phi
      - Mm_mu2_pt
      - Mm_mu2_eta
      - Mm_mu2_phi
      - Muon_softMva1
      - Muon_softMva2
      - Muon_charge1
      - Muon_charge2
      - Muon_Dxy1
      - Muon_Dxy2
      - Muon_Dz1
      - Muon_Dz2

  Jpsi:
    limits:
      inclusive: (2.6,3.56)
      signal: 
        - ()
      background:
        - ()
        - ()
    train_vars:
      - Mm_kin_lxy
      - Mm_kin_l3d
      - Mm_kin_sl3d
      - Mm_kin_vtx_chi2dof
      - Mm_kin_vtx_prob
      - Mm_kin_alpha
      - Mm_kin_alphaBS
      - Mm_closetrk
      - Mm_closetrks1
      - Mm_closetrks2
      - Mm_kin_pvip
      - Mm_kin_spvip
      - Mm_kin_eta    
      - Mm_kin_pvlip
      - Mm_kin_slxy
      - Mm_iso
      - Mm_otherVtxMaxProb
      - Mm_otherVtxMaxProb1
      - Mm_otherVtxMaxProb2
    other_vars:
      - Mm_mass
      - Mm_mu1_pt
      - Mm_mu1_eta
      - Mm_mu1_phi
      - Mm_mu2_pt
      - Mm_mu2_eta
      - Mm_mu2_phi
      - Muon_softMva1
      - Muon_softMva2
      - Muon_charge1
      - Muon_charge2
      - Muon_Dxy1
      - Muon_Dxy2
      - Muon_Dz1
      - Muon_Dz2

sPlot: 
 - 