executable = /work/submit/mori25/Darkphotons_ludo/offline_analysis/pull_data/offline/run_merge_off_full.sh
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = /work/submit/mori25/Darkphotons_ludo/offline_analysis/pull_data/offline/list_offline.txt,/work/submit/mori25/Darkphotons_ludo/offline_analysis/pull_data/offline/generateOffDimuonTree.C
transfer_output_files = ""
# MyIndex=$(ProcId)
#Extention=$INT(MyIndex,%d)
arguments = "$(MyIndex)"
Requirements = ( BOSCOCluster =!= "t3serv008.mit.edu" && BOSCOCluster =!= "ce03.cmsaf.mit.edu" && BOSCOCluster =!= "eofe8.mit.edu")
# +REQUIRED_OS = "rhel7"
+DESIRED_Sites = "mit_tier3,mit_tier2"  
use_x509userproxy = True
x509userproxy = /home/submit/mori25/x509up_u238361
output = /data/submit/mori25/dark_photons_ludo/DimuonTrees/offline/logs/job.$(MyIndex).out
error = /data/submit/mori25/dark_photons_ludo/DimuonTrees/offline/logs/job.$(MyIndex).err
log = /data/submit/mori25/dark_photons_ludo/DimuonTrees/offline/logs/job.$(MyIndex).log
#RequestMemory = 4000
Universe = vanilla
queue MyIndex in 1324,130,178,212
