executable = /work/submit/mori25/Darkphotons_ludo/other_utils/test_condor/script.sh
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
#transfer_input_files = /work/submit/mori25/Darkphotons_ludo/offline_analysis/pull_data/MC_InclusiveMinBias/list_InclMinBias.txt,/work/submit/mori25/Darkphotons_ludo/offline_analysis/pull_data/MC_InclusiveMinBias/generateMCDimuonTree.C
transfer_output_files = ""
MyIndex=$(ProcId)
Extention=$INT(MyIndex,%d)
arguments = "$(Extention)"
Requirements = ( BOSCOCluster =!= "t3serv008.mit.edu" && BOSCOCluster =!= "ce03.cmsaf.mit.edu" && BOSCOCluster =!= "eofe8.mit.edu")
# +REQUIRED_OS = "rhel7"
+DESIRED_Sites = "mit_tier3,mit_tier2"
use_x509userproxy = True
x509userproxy = /home/submit/mori25/x509up_u238361
output = /work/submit/mori25/Darkphotons_ludo/other_utils/test_condor/job.$(Process).out
error = /work/submit/mori25/Darkphotons_ludo/other_utils/test_condor/job.$(Process).err
log = /work/submit/mori25/Darkphotons_ludo/other_utils/test_condor/job.$(Process).log
#RequestMemory = 4000
Universe = vanilla
queue 1